language: android

android:
  components:
  - build-tools-28.0.3
  - android-28
  - extra-google-m2repository
  - extra-android-m2repository

before_deploy: openssl aes-256-cbc
  -K $encrypted_83b258603a40_key
  -iv $encrypted_83b258603a40_iv
  -in secring.gpg.enc
  -out secring.gpg -d

deploy:
- provider: script
  script: ./gradlew uploadArchives
    -PossrhUsername='$SONATYPE_USERNAME'
    -PossrhPassword='$SONATYPE_PASSWORD'
    -Psigning.keyId='$SIG_KEY'
    -Psigning.password='$SIG_PASS'
    -Psigning.secretKeyRingFile='../$SIG_FILE'
  skip_cleanup: true
  on:
    branch: develop
- provider: script
  script: ./gradlew uploadArchives
    -PossrhUsername='$SONATYPE_USERNAME'
    -PossrhPassword='$SONATYPE_PASSWORD'
    -Psigning.keyId='$SIG_KEY'
    -Psigning.password='$SIG_PASS'
    -Psigning.secretKeyRingFile='../$SIG_FILE'
  skip_cleanup: true
  on:
    tags: true
    branch: master
